version: "3"

services:  
  app:
    #image: platziapp
    build: .
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000-3010:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  db:
    image: mongo

  #nginx:
  #  image: nginx:alpine #Esta realizado para un servidor (no varios)
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #  links:
  #    - app     
  #  ports:
  #    - "4000-4010:8008"
